import { Jura } from "next/font/google";
import "./globals.css";
//Ubuntu is alternative

const ubuntu = Jura({ 
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Airborne Cinema",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
